"""add SystemSettings table

Revision ID: 31882e67f128
Revises: g7h8i9j0k1l2
Create Date: 2026-04-27 19:20:58.694842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31882e67f128'
down_revision = 'g7h8i9j0k1l2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SystemSettings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('AdminUsers', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_AdminUsers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_AdminUsers_venue_id'), ['venue_id'], unique=False)
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Bookings_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_Bookings_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_Bookings_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Bookings_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('Description_en',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_Categories_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Categories_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('FoodItems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_FoodItems_CategoryID'), ['CategoryID'], unique=False)
        batch_op.create_index(batch_op.f('ix_FoodItems_SubcategoryID'), ['SubcategoryID'], unique=False)

    with op.batch_alter_table('GlobalItems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_globalitems_category_id'))
        batch_op.drop_index(batch_op.f('ix_globalitems_subcategory_id'))
        batch_op.create_index(batch_op.f('ix_GlobalItems_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_GlobalItems_subcategory_id'), ['subcategory_id'], unique=False)

    with op.batch_alter_table('GlobalSubcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GlobalSubcategories_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Orders_Status'), ['Status'], unique=False)
        batch_op.create_index(batch_op.f('ix_Orders_TableID'), ['TableID'], unique=False)
        batch_op.create_index(batch_op.f('ix_Orders_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('Promotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Promotions_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('RestaurantTables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_RestaurantTables_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('Subcategories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Subcategories_CategoryID'), ['CategoryID'], unique=False)

    with op.batch_alter_table('VenueFeatureOverrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_VenueFeatureOverrides_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('VenueGroupInvites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_VenueGroupInvites_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_VenueGroupInvites_invited_by'), ['invited_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_VenueGroupInvites_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_VenueGroupInvites_target_venue_id'), ['target_venue_id'], unique=False)

    with op.batch_alter_table('VenueGroups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_VenueGroups_owner_venue_id'), ['owner_venue_id'], unique=False)

    with op.batch_alter_table('VenueItemPriceOverrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_VenueItemPriceOverrides_food_item_id'), ['food_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_VenueItemPriceOverrides_venue_id'), ['venue_id'], unique=False)

    with op.batch_alter_table('Venues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Venues_group_id'), ['group_id'], unique=False)
        batch_op.create_unique_constraint(None, ['venue_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_Venues_group_id'))

    with op.batch_alter_table('VenueItemPriceOverrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_VenueItemPriceOverrides_venue_id'))
        batch_op.drop_index(batch_op.f('ix_VenueItemPriceOverrides_food_item_id'))

    with op.batch_alter_table('VenueGroups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_VenueGroups_owner_venue_id'))

    with op.batch_alter_table('VenueGroupInvites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_VenueGroupInvites_target_venue_id'))
        batch_op.drop_index(batch_op.f('ix_VenueGroupInvites_status'))
        batch_op.drop_index(batch_op.f('ix_VenueGroupInvites_invited_by'))
        batch_op.drop_index(batch_op.f('ix_VenueGroupInvites_group_id'))

    with op.batch_alter_table('VenueFeatureOverrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_VenueFeatureOverrides_venue_id'))

    with op.batch_alter_table('Subcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Subcategories_CategoryID'))

    with op.batch_alter_table('RestaurantTables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_RestaurantTables_venue_id'))

    with op.batch_alter_table('Promotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Promotions_venue_id'))

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Orders_venue_id'))
        batch_op.drop_index(batch_op.f('ix_Orders_TableID'))
        batch_op.drop_index(batch_op.f('ix_Orders_Status'))

    with op.batch_alter_table('GlobalSubcategories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GlobalSubcategories_category_id'))

    with op.batch_alter_table('GlobalItems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GlobalItems_subcategory_id'))
        batch_op.drop_index(batch_op.f('ix_GlobalItems_category_id'))
        batch_op.create_index(batch_op.f('ix_globalitems_subcategory_id'), ['subcategory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_globalitems_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('FoodItems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_FoodItems_SubcategoryID'))
        batch_op.drop_index(batch_op.f('ix_FoodItems_CategoryID'))

    with op.batch_alter_table('Categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Categories_venue_id'))
        batch_op.drop_index(batch_op.f('ix_Categories_group_id'))
        batch_op.alter_column('Description_en',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('Description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('Bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Bookings_venue_id'))
        batch_op.drop_index(batch_op.f('ix_Bookings_table_id'))
        batch_op.drop_index(batch_op.f('ix_Bookings_status'))
        batch_op.drop_index(batch_op.f('ix_Bookings_customer_id'))
        batch_op.drop_index(batch_op.f('ix_Bookings_booking_date'))

    with op.batch_alter_table('AdminUsers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_AdminUsers_venue_id'))
        batch_op.drop_index(batch_op.f('ix_AdminUsers_phone'))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    op.drop_table('SystemSettings')
    # ### end Alembic commands ###
